### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by GigiLi89** [GigiLi89/love-running#1]
As a photographer, I can show information about my camera gear to others so that others can find information about the gear easily. 

**Acceptance Criteria:**
a) Information/presentation page about the camera gear 
b) Divide each equipment to keep it a clear and easy to locate information page. 

**Tasks:**
- [ ] Design a clear and functional Gear Information page 
- [ ] Using HTML and CSS, create sections for the gear information with a collage look. Photo and description text under the photo.  
- [ ] Add Media query with CSS to fit the information on different devices. 
- [ ] Add information about the gear into the different sections

**Comment by GigiLi89** [comment]
closed
